sonar.projectKey=api-projeto
sonar.projectName=API Projeto
sonar.sources=src
sonar.tests=tests
sonar.language=java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
